### PR TITLE
Lots of changes

### PR DESCRIPTION
**Pull request by TacoTheDank**
- Delete generated files
- Delete unused findbugs plugin
- Update Android Studio 3.2.1 -> 3.3.0
- Update Gradle 4.10 -> 5.2-RC1
- Update Fastlane to 2.115.0 (hopefully I did that right)
- Update TarsosDSP library to the latest commit (https://github.com/JorenSix/TarsosDSP/tree/c26e5004e203ee79be1ec25c2603b1f11b69d276)
- Update README with a couple of misc changes
- Set encoding to UTF-8
- Rearrange and update dependencies (material-spinner 1.3.0 -> 1.3.1, number-picker 2.4.6 -> 2.4.7, hamcrest 1.3 -> 2.1, powermock 1.7.4 -> 2.0.0, junit 4.12 -> 4.13-beta-1)
- Replace Note qualifiers with imports
- Extract some strings from code into string files and rearranged strings
- Migrate App to AppCompat
- Migrate to AndroidX

### CODE REVIEW

**Comment by gstraube** [comment]
Very nice, thanks a lot!

**Comment by TacoTheDank** [comment]
👍 :P

**Comment by TacoTheDank** [comment]
Oh my, it's crashing at startup?

@gstraube Try installing [this](https://forum.xda-developers.com/android/apps-games/adb-root-scoop-catch-stack-trace-app-t3888798) and granting ```adb shell pm grant xyz.paphonb.scoop android.permission.READ_LOGS``` via ADB (for unrooted), or via root (for rooted). The apks can be found here: https://paphonb.xyz/android/apps/scoop/

This should help you determine the cause, instead of having to go through reverting the entire commit and sifting through every change just to see why it's crashing. I wouldn't want you to have to do that xd

**Comment by TacoTheDank** [comment]
So I locally cloned the repo and built an apk, and here are the results in a video. https://streamable.com/4p7fk
I have a Note 9 running Android Pie (API 28).

What's causing the set reference pitch failure is the supportFragmentManager ([this](https://github.com/gstraube/cythara/commit/3624c8a94baa0fae29e2f362d1c78521017309c5#diff-6432894361c0c07119cab477face872bR154), [this](https://github.com/gstraube/cythara/commit/3624c8a94baa0fae29e2f362d1c78521017309c5#diff-6432894361c0c07119cab477face872bR231), and [this](https://github.com/gstraube/cythara/commit/3624c8a94baa0fae29e2f362d1c78521017309c5#diff-dab4c0da85263cb0bf490d5a866b1985R59)), which is something I did to make the app not error out when sync-building gradle in Android Studio. Said error appeared after migrating App to AppCompat. I don't know how to fix it, so I just did what Android Studio suggested and added that third "this" :/

**Comment by gstraube** [comment]
I [changed the base class](https://github.com/gstraube/cythara/commit/a1a1ba3d8f135589478616a8c95b31300a1e9d80) of NumberPickerDialog to make the dialog appear again.

Unfortunately, I lost the keystore which I used on the Play Store and it is not allowed to sign the app with a new key. Therefore, I can only update the app on F-Droid and Github but not on the Play Store (it would have to be re-published as another app).

**Comment by TacoTheDank** [comment]
Oof. There's a thing I heard about Google developing a signature called v3 (from what I remember, different key support?)? Would be interesting to look into...

**Comment by TacoTheDank** [comment]
@gstraube It's a bit late to say this, but it wouldn't hurt to practice in the future.

Make backups of your keystore files in cloud storages and thumb drives ;)

**Comment by gstraube** [comment]
The [app signing program](https://support.google.com/googleplay/android-developer/answer/7384423) allows for changing keys but it is not possible to enroll with a key that differs from the one already used for manually signing the APK. I will definitely include the keystore in my backups now. Guess I had to learn that the hard way.

**Comment by TacoTheDank** [comment]
Lol

Is it possible to delete and re-upload the app to the Play Store to prevent having to rename the app id?

**Comment by gstraube** [comment]
It seems to be possible (https://stackoverflow.com/questions/21546047/in-playstore-can-we-have-two-apps-with-same-name-with-different-package-androi) but apparently there is no way to notify current users.

**Comment by TacoTheDank** [comment]
Hmm

**Pull request merged**
